### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kroggen** [rigtorp/awesome-lockfree#1]
What about the http://liblfds.org/ ?

**Comment by rigtorp** [comment]
I've looked at it, but benchmarks with no axis labels, documentation doesn't load etc, can't recommended it. Maybe it's great, but if so they need to do a better job showing my why.

**Comment by raedwulf** [comment]
...but they do actually write what the labels of the axes are above the graphs.  The author does have a strange approach to releasing software and their repository is frankly... non-standard... but they have code!

**Comment by rigtorp** [comment]
I've added it now.
