### ISSUE TITLE
Xenium

### ISSUE THREAD

**Issue by mpoeter** [rigtorp/awesome-lockfree#2]
Hi,

I am working on a C++ library called "Xenium" that provides various concurrent data structures and memory reclamation schemes: https://github.com/mpoeter/xenium
Maybe you can take a look at it and add it to your list. 🙂 

Cheers,
Manuel

**Comment by rigtorp** [comment]
Looks nice! Added it. Have you looked at the proposed APIs for standardizing RCU and hazard pointers?

**Comment by mpoeter** [comment]
Thanks! Yes, I did have a look at the RCU and hazard pointer proposals, but I prefer the one by Robison as it is more generic. It allowed me to implement a large number of reclamation schemes together with different characteristics, as well as concurrent data structures that are completely agnostic of the used reclamation scheme.

Feedback (and of course also contributions) is highly welcome! 🙂
