### ISSUE TITLE
Intel oneTBB?

### ISSUE THREAD

**Issue by kkm000** [rigtorp/awesome-lockfree#6]
Hi, thanks for keeping the list, a nice collection! I do not know if [Intel's oneTBB](https://github.com/oneapi-src/oneTBB), neé TBB, belongs in. Its not a “lock-free” library, rather a “don't think about locks and build robust high-throughput HPC software that scales” library. At the core, it uses both locking and lock-free algorithms, and takes care about task affinity, data cache locality, per-thread memory allocation to reduce allocation contention, and other crazy stuff. But most of this stuff is deep at the core; it focuses on high-level design blocks (hence the name). xPxC queues and other concurrent containers are probably among the lowest level algorithms which it surfaces. Up to you.

**Comment by rigtorp** [comment]
TBB is nice but more of a general parallel programming framewrok.
